### ISSUE TITLE
Fails to load in latest NINA

### ISSUE THREAD

**Issue by RReverser** [sshh12/astro-app-nina-api#1]
Getting this error when attempting to add plugin to latest version of NINA (3.1 HF2):

![image](https://github.com/user-attachments/assets/026488f2-db49-46fc-9761-a31142aee447)

Here's a detailed log from NINA log file:

```
2024-11-03T00:46:35.1002|ERROR|PluginLoader.cs|LoadPlugin|462|Failed to load plugin at C:\Users\me\AppData\Local\NINA\Plugins\3.0.0\Astro HTTP API\Plugin.NINA.AstroAppHTTPAPI.dll - Astro HTTP API version 1.0.1.2 The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi'.

Resulting in: Cannot activate part 'Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi'.
Element: Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi -->  Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi -->  AssemblyCatalog (Assembly="Plugin.NINA.AstroAppHTTPAPI, Version=1.0.1.2, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi (ContractName="NINA.Plugin.Interfaces.IPluginManifest")' from part 'Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi'.
Element: Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi (ContractName="NINA.Plugin.Interfaces.IPluginManifest") -->  Plugin.NINA.AstroAppHTTPAPI.AstroAppHttpApi -->  AssemblyCatalog (Assembly="Plugin.NINA.AstroAppHTTPAPI, Version=1.0.1.2, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'NINA.Plugin.ManifestImport.PluginManifestImport (ContractName="NINA.Plugin.Interfaces.IPluginManifest")' on part 'NINA.Plugin.ManifestImport'.
Element: NINA.Plugin.ManifestImport.PluginManifestImport (ContractName="NINA.Plugin.Interfaces.IPluginManifest") -->  NINA.Plugin.ManifestImport
```

**Comment by sshh12** [comment]
Hey! I think the initial setup might be a bit bugged. Does the issue go away once you restart NINA? That seems to be the work around right after a fresh install.

**Comment by RReverser** [comment]
It didn't seem to, but now that I updated the plugin, it seems to load just fine... very odd, given that the only change is to static content, judging by the commit history.

Either way, closing the issue. Thanks!

**Comment by RReverser** [comment]
It doesn't seem https://astroapp.io/image/nina can work with it yet though. Or maybe I'm missing something.

![image](https://github.com/user-attachments/assets/12187d8e-089f-4ea0-b7d3-0aeb694f9abe)

![image](https://github.com/user-attachments/assets/8bb53f3f-cd67-4e16-a84e-934207042908)

**Comment by sshh12** [comment]
Hmm it should but looks like it's running into a weird issue.

**Comment by sshh12** [comment]
Let me take a deeper look this week and try to reproduce.

**Comment by sshh12** [comment]
This is fixed! https://github.com/sshh12/astro-app-nina-api/issues/2
