### ISSUE TITLE
"Unexpected token '<', "<!DOCTYPE "... is not valid JSON" issue

### ISSUE THREAD

**Issue by jin-young** [sshh12/astro-app-nina-api#2]
Hi,

I tried to access NINA through https://astroapp.io/image/nina but failed with the error message in subject.

It is local connect: https://127.0.0.1:8181 with the API key from NINA's plugin page as a password in the astroapp.io's page.

The plugin version is 1.0.1.3 and NINA version is 3.1 HF2. Port in the plugin is set to 8181.

May I get some help on this?

**Comment by aazmatius** [comment]
+ 

same problem

**Comment by sshh12** [comment]
Hi all sorry about this -- was a bug I introduced in the last update without testing.

Should be fixed now in version `1.0.1.4`.
